### ISSUE TITLE
JSONCオートフォーマッター

### ISSUE THREAD

**Issue by book000** [jaoafa/CrimicCosmos#25]
JSONの自動フォーマッティングをしたいよね
コメントありっぽいからJSONCで処理?
自動でコミット投げることの是非は難しい

**Comment by book000** [comment]
https://qiita.com/buyoh/items/183b20f7c4bd2846028c

**Comment by book000** [comment]
https://github.com/microsoft/node-jsonc-parser

**Comment by book000** [comment]
http://helmet.kafuka.org/sbmods/json/

**Comment by book000** [comment]
サポートする拡張子一覧: https://starbounder.org/Modding:JSON_Object_Types

**Comment by book000** [comment]
Fork先からプルリクを作成された場合にリントコミットをプッシュできないので泣く泣くクローズ

```yaml
name: Code Formatter with book000/starbound-jsonc-formatter

on:
  pull_request_target:
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ github.token }}

      - name: Run book000/starbound-jsonc-formatter
        uses: book000/starbound-jsonc-formatter@master
        
      - name: check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Set git config
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config pull.rebase true
      - name: push changes
        id: push-changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git commit -am "fix: apply jsonc format"
          git push --force https://${{ github.token }}@github.com/${{ github.event.pull_request.head.repo.full_name }}
```
